## Database Properties
spring.datasource.url=${POSTGRES_DATA_SOURCE_URL}
spring.datasource.username=${POSTGRES_USER}
spring.datasource.password=${POSTGRES_PASSWORD}
spring.jpa.show-sql=${SPRING_JPA_SHOW_SQL}

## Hibernate Properties
spring.jpa.properties.hibernate.dialect=${SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT}
spring.jpa.hibernate.ddl-auto=validate

## Logging
logging.level.root=INFO

## SSL
server.ssl.enabled=false
server.port=8083

# Redis
spring.data.redis.host=${REDIS_HOST}
spring.data.redis.port=${REDIS_PORT}
spring.data.redis.timeout=2000
# 15 min
spring.cache.redis.time-to-live=900000

# Stats with Prometheus and Grafana
management.endpoints.web.exposure.include=health,info,metrics,prometheus
management.prometheus.metrics.export.enabled=true
management.endpoint.prometheus.enabled=true

# Resilience4j
resilience4j.ratelimiter.instances.scrapService.limit-for-period=3
resilience4j.ratelimiter.instances.scrapService.limit-refresh-period=1s
resilience4j.ratelimiter.instances.scrapService.timeout-duration=30s

# Spring
spring.profiles.active=${SPRING_PROFILES_ACTIVE}

# Spring AI
spring.ai.openai.api-key=ollama
spring.ai.openai.base-url=http://localhost:11434/
spring.ai.openai.chat.options.model=mistral:7b